---
- name: common | brew update (1)
  homebrew: update_homebrew=yes

- name: common | brew tap (taps)
  with_items: taps
  homebrew_tap: name={{ item }} state=present

- name: common | brew update (2)
  homebrew: update_homebrew=yes upgrade_all=yes

- name: common | brew install (packages)
  with_items: packages
  homebrew: name={{ item }} state=upgraded

- name: common | brew cask install (casks)
  with_items: casks
  homebrew_cask: name={{ item }} state=installed
